/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* --- RCC REGISTERS --- */
#define RCC_BASE        (0x40023800U) // RCC Base Address
#define RCC_AHB1ENR     (*((volatile uint32_t *)(RCC_BASE + 0x30u))) // RCC clock for GPIO
#define RCC_APB2ENR     (*((volatile uint32_t *)(RCC_BASE + 0x44u))) // Dùng để cấp clock cho bộ kết nối ngắt SYSCFG.

/* --- GPIO REGISTERS --- */
#define GPIOA_BASE      (0x40020000U) // Base address of GPIO PORT A
#define GPIOA_MODER     (*((volatile uint32_t *)(GPIOA_BASE + 0x00u)))
#define GPIOA_ODR       (*((volatile uint32_t *)(GPIOA_BASE + 0x14u)))

#define GPIOC_BASE      (0x40020800U) // Base address of GPIO PORT C
#define GPIOC_MODER     (*((volatile uint32_t *)(GPIOC_BASE + 0x00u)))

/* --- 1. NHÓM SYSCFG --- */
#define SYSCFG_BASE     (0x40013800U) // Base address of System configure
#define SYSCFG_EXTICR4  (*((volatile uint32_t *)(SYSCFG_BASE + 0x14u))) // Configure EXTI13 for PC13

/* --- 2. NHÓM EXTI --- */
#define EXTI_BASE       (0x40013C00U)
#define EXTI_IMR        (*((volatile uint32_t *)(EXTI_BASE + 0x00u))) // Configure Interrupt mask register (EXTI_IMR)
#define EXTI_FTSR       (*((volatile uint32_t *)(EXTI_BASE + 0x0Cu))) // Configure Falling trigger selection register when push the button
#define EXTI_PR         (*((volatile uint32_t *)(EXTI_BASE + 0x14u))) // Pending register

/* --- 3. NHÓM NVIC (LÕI CORTEX-M4) --- */
#define NVIC_ISER1      (*((volatile uint32_t *)(0xE000E104U))) // ISER1 manages IRQ 32 to 63 (EXTI15_10 is IRQ 40)

/* --- HÀM XỬ LÝ NGẮT (INTERRUPT SERVICE ROUTINE - ISR) --- */
void EXTI15_10_IRQHandler(void)
{
    // Kiểm tra cờ ngắt Pending của EXTI13
    if (EXTI_PR & (1U << 13))
    {
        // Đảo trạng thái LED PA5
        GPIOA_ODR ^= (1U << 5);

        // Xóa cờ ngắt (Ghi bit 1 vào EXTI_PR để xóa)
        EXTI_PR = (1U << 13);
    }
}

int main(void)
{
    /* Bước 1: Bật clock cho GPIOA, GPIOC và SYSCFG */
    RCC_AHB1ENR |= ((1u << 0) | (1u << 2)); // Bật clock cho GPIOA và GPIOC tại bit 0 & bit 2
    RCC_APB2ENR |= (1u << 14);              // Bật clock cho SYSCFG tại bit 14

    /* Bước 2: Cấu hình GPIO Mode */
    GPIOA_MODER &= ~(3u << 10);
    GPIOA_MODER |=  (1u << 10); // Set mode PA5 = output (01 ở bit 11:10)

    GPIOC_MODER &= ~(3u << 26); // Set mode PC13 = input (00 ở bit 27:26)

    /* Bước 3: Cấu hình SYSCFG (Trỏ EXTI13 về Port C / PC13) */
    SYSCFG_EXTICR4 &= ~(0xFu << 4); // Clear 4 bit [7:4]
    SYSCFG_EXTICR4 |=  (0x2u << 4); // Ghi 0x2 (Port C) vào bit [7:4]

    /* Bước 4: Cấu hình EXTI (Kích hoạt ngắt cạnh xuống & Unmask đường EXTI13) */
    EXTI_FTSR |= (1u << 13); // Trigger cạnh xuống (khi bấm nút)
    EXTI_IMR  |= (1u << 13); // Unmask / Cho phép ngắt trên đường EXTI13

    /* Bước 5: Cấu hình NVIC (Bật ngắt tổng cho kênh EXTI15_10 - IRQ 40 -> Bit 8 trong ISER1) */
    NVIC_ISER1 |= (1u << 8);

    for (;;)
    {
        /* Everything is handled in EXTI15_10_IRQHandler */
    }
}
